name: ElectricSpock Release CI

on:
  push:
    branches: [ release ]

jobs:
  build:
    uses: gradle/gradle-build-action@v2
    with:
      arguments: clean test publish
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}